// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gckonoxrhoviztrvqlld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdja29ub3hyaG92aXp0cnZxbGxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyNzI5OTcsImV4cCI6MjA5MTg0ODk5N30.uqv1uUAW30mWs7oIfEEFhvVz9hBNznswnU2QoJnue4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});